baseURL = "https://kevinhumesfoundation.netlify.app/"
languageCode = "en-us"
title = "Kevin Humes Memorial Foundation"
theme = "ananke"

SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number


[menu]
  [[menu.main]]
    name = "Kevin's Story"
    identifier = "story"
    url = "/story/"
    weight = 1
  [[menu.main]]
    name = "Store"
    identifier = "store"
    url = "https://kevin-humes-memorial-foundation.square.site"


[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "/images/logo.png"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
  Copyright = "Test"
  custom_css = ["custom.css"]

[[params.ananke_socials]]
name = "facebook"
url = "https://www.facebook.com/pages/category/Nonprofit-organization/Kevin-Humes-Memorial-Foundation-104230661794286/"
